import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Wildwood Honey",
    slug: "wildwood-honey",
    bio: "Raw, unfiltered honey from 80 hives set among the ancient oaks and wildflower meadows of Sherwood Forest. Every jar is cold-extracted and hand-labelled on our small family farm in Ollerton.",
    story:
      "I stumbled into beekeeping after retiring from the NHS in 2012 — what started as two hives in the back garden has grown into something we never imagined. Today we manage 80 hives across five distinct sites in Nottinghamshire, each producing honey with its own character. We've never heated our honey above ambient temperature and we never will. The enzymes, pollen, and flavour compounds that make raw honey special are destroyed by heat — so we cold-extract everything slowly and bottle it straight from the apiary. Some of our honey ends up on the tables of Michelin-starred restaurants in Nottingham. Most of it ends up in the kitchens of local families, and that's exactly where we want it to be.",
    location: "Sherwood Forest, Nottinghamshire",
    address: {
      line1: "Forest Edge Cottage, Ollerton Road",
      city: "Ollerton",
      county: "Nottinghamshire",
      postcode: "NG22 9AJ",
      country: "GB",
    },
    categories: ["honey", "preserves"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/raw-honey.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@wildwoodhoney",
      facebook: "WildwoodHoneyNottinghamshire",
    },
    rating: 4.9,
    reviewCount: 312,
    createdAt: new Date("2012-04-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Sherwood Wildflower Honey",
    description:
      "Our signature honey — raw and cold-extracted from hives set among heather, clover, bramble, and wildflowers on the Sherwood Forest margins. A light, floral, and gently sweet honey that works equally well on toast, in tea, or straight from the spoon. Crystallises naturally to a smooth, spreadable set over several months.",
    slug: "sherwood-wildflower-honey",
    category: "honey",
    price: 850,
    unit: "340g jar",
    stock: 148,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Heather Honey",
    description:
      "Our most prized single-varietal — harvested once a year in late August when the Nottinghamshire heathland is in full bloom. Deep amber in colour with a thixotropic set that's unique to heather honey. Intensely aromatic, complex, and earthy. Limited run each season — once it's gone, it's gone until next year.",
    slug: "heather-honey",
    category: "honey",
    price: 1250,
    unit: "340g jar",
    stock: 42,
    images: [
      "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Raw Honeycomb",
    description:
      "Freshly cut comb honey — beeswax, nectar, and all. The bees build and fill the comb themselves; we simply cut and box it. Eat it with cheese, crumble it over yoghurt, or slice it onto sourdough. The most natural form of honey that exists.",
    slug: "raw-honeycomb",
    category: "honey",
    price: 995,
    unit: "200g box",
    stock: 36,
    images: [
      "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Creamed Wildflower Honey",
    description:
      "Our wildflower honey whipped to a silky, spreadable cream. Same raw honey, same cold extraction — just processed slowly to create a uniform fine crystal. Stays soft at room temperature, spreads like butter, and tastes extraordinary. Popular with customers who prefer a honey that doesn't drip.",
    slug: "creamed-honey",
    category: "honey",
    price: 875,
    unit: "340g jar",
    stock: 95,
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Honey Tasting Collection",
    description:
      "Three of our finest honeys in a gift-ready wooden box — our Sherwood Wildflower, Creamed Wildflower, and Heather Honey. Perfect for exploring the range or giving as a gift. Each jar is 227g. Includes a tasting notes card describing each variety.",
    slug: "honey-tasting-collection",
    category: "honey",
    price: 2850,
    unit: "3 × 227g gift box",
    stock: 28,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Beeswax Pillar Candles (pair)",
    description:
      "Hand-poured pillar candles made from 100% pure beeswax recovered from our hives during the honey harvest. Beeswax burns cleaner and longer than paraffin and emits a gentle, natural honey scent as it melts. Each pair burns for approximately 40 hours.",
    slug: "beeswax-candles",
    category: "preserves",
    price: 1400,
    unit: "pair",
    stock: 54,
    images: [
      "/images/beeswax-candles.jpg",
    ],
    dietary: [],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Ginger & Honey Throat Soother",
    description:
      "A warming blend of our raw wildflower honey with cold-pressed ginger juice and a touch of lemon oil. Stir into hot water, drizzle over porridge, or take straight from the spoon at the first sign of a sniffle. No artificial preservatives — just honey, ginger, and lemon.",
    slug: "ginger-honey-throat-soother",
    category: "preserves",
    price: 795,
    unit: "250g jar",
    stock: 67,
    images: [
      "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=800&q=80",
    ],
    dietary: ["gluten-free", "dairy-free", "vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Wildwood Honey",
    producerSlug: "wildwood-honey",
    name: "Pure Beeswax Block",
    description:
      "A 100g block of raw, unbleached beeswax from our hives. Beloved by woodworkers, leatherworkers, knitters, and makers of all kinds. Natural golden colour, clean honey scent. Also used in homemade lip balms, hand creams, and furniture polish.",
    slug: "beeswax-block",
    category: "preserves",
    price: 650,
    unit: "100g block",
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    dietary: [],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "I've been buying honey from supermarkets my whole life — this is a completely different product. The wildflower honey has a depth of flavour I didn't know honey could have. Two jars a month minimum now.",
    createdAt: new Date("2024-03-02"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The heather honey is extraordinary. I served it at a dinner party with a strong blue cheese and it was the talking point of the evening. Already ordered another two jars before the season ends.",
    createdAt: new Date("2024-03-08"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Emma R.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The gift box was the perfect present for my mum — she's been raving about it ever since. The tasting notes card was a lovely touch. Fast shipping and beautiful packaging too.",
    createdAt: new Date("2024-03-15"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "Sherwood Wildflower Honey",
        producerId: "producer-1",
        producerName: "Wildwood Honey",
        price: 850,
        quantity: 2,
        unit: "340g jar",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-5",
        productName: "Honey Tasting Collection",
        producerId: "producer-1",
        producerName: "Wildwood Honey",
        price: 2850,
        quantity: 1,
        unit: "3 × 227g gift box",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "8 Castle Gate",
      city: "Nottingham",
      postcode: "NG1 7AS",
      country: "GB",
    },
    subtotal: 4550,
    commission: 0,
    deliveryFee: 395,
    total: 4945,
    stripePaymentIntentId: "pi_demo_honey_001",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-12"),
  },
];
